# .github/workflows/deploy.yml
name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io  # Docker Hub registry
  IMAGE_NAME: openrangedevs/kamal
  KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3
        with:
          username: openrangedevs
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest

      - name: Install Kamal
        run: sudo gem install kamal

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Kamal
        run: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
          kamal deploy
